server:
  port: 8080
  servlet:
    context-path: /

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: default
  main:
    allow-circular-references: true
  application:
    name: book-store
  datasource:
    url: jdbc:postgresql://localhost:5432/webbook
    username: postgres
    password: Pershakov757
    driverClassName: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
        hbm2ddl:
          import_files: init.sql
          auto: create
    hibernate:
      ddl-auto: create
    generate-ddl: true
  sql.init.mode: never

logging:
  level:
    org.springframework.orm.jpa: ERROR
    jdbc:
      sqlonly: ERROR
      audit: ERROR
      sqltiming: DEBUG
      resultset: ERROR
      connection: ERROR

log4jdbc:
  drivers: org.postgresql.Driver
  auto:
    load:
      popular:
        drivers: false
  dump:
    sql:
      select: true
      update: true
      insert: true

springdoc:
  api-docs:
    enabled: true
    path: /rest-api-docs
  swagger-ui:
    path: /swagger-ui